// src/app/layout.tsx
import './globals.css'; // 保持全域樣式
import '@mantine/core/styles.css'; // 引入 Mantine 核心樣式
import '@mantine/notifications/styles.css'; // 引入通知元件樣式
import '@mantine/dates/styles.css'; // 引入日期選擇器樣式
import { Inter } from 'next/font/google';
import { Providers } from './providers'; // 引入 Providers 元件

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My Next.js Side Project',
  description:
    'A Next.js side project with Mantine, Tailwind CSS and React Query.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head> */}
      <body className={inter.className}>
        <Providers>
          {' '}
          {/* 將 children 包裹在 Providers 內部 */}
          {children}
        </Providers>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
